// apps/admin/src/pages/EditorNew/components/editor.tsx
import type React from "react";
import {
  useRef,
  useEffect,
  useState,
  useMemo,
  useCallback,
  forwardRef,
  useImperativeHandle,
} from "react";
import { Modal } from "antd";
import _ from "lodash";
import { Editor } from "@plux/editor";

// Custom hook to replace useElementSize from @vueuse/core
const useElementSize = (elementRef: React.RefObject<HTMLElement | null>) => {
  const [size, setSize] = useState({ width: 0, height: 0 });

  useEffect(() => {
    const element = elementRef.current;
    if (!element) return;

    const resizeObserver = new ResizeObserver((entries) => {
      for (const entry of entries) {
        const { width, height } = entry.contentRect;
        setSize({ width, height });
      }
    });

    resizeObserver.observe(element);

    return () => {
      resizeObserver.disconnect();
    };
  }, []);

  return size;
};

const FlowchartEditor = forwardRef(
  (
    {
      theme = "dark",
      isEdit = false,
      animation = true,
      mode = "A",
      intersection = false,
      defaultPipeline = false,
      showBindBtn = false,
      scroll = false,
      touch = false,
      history = false,
      selected = null,
      gridSize = 30,
      gridFixed = false,
      viewStyle = 0,
      lineTop = false,
      onClick,
      onDrop,
      onSelect,
      onDragmove,
      onModeChange,
      onKeydown,
      onCreateLine,
      onRemove,
      onMessage,
      onDo,
      onTouch,
      title,
      tools,
      extra,
      selectedValue,
      onSelectedChange,
      modeValue,
      onModeValueChange,
    },
    ref
  ) => {
    const editorRef = useRef<HTMLDivElement>(null);
    const editorWrapRef = useRef<HTMLDivElement>(null);
    const editorInstance = useRef<Editor | null>(null);

    const { width, height } = useElementSize(editorRef);

    const debounceToFit = useMemo(
      () =>
        _.debounce(() => {
          if (editorInstance.current) {
            editorInstance.current.fitStage();
          }
        }, 300),
      []
    );

    useEffect(() => {
      debounceToFit();
    }, [width, height, debounceToFit]);

    const currentMode = useMemo(() => {
      return modeValue !== undefined ? modeValue : mode;
    }, [modeValue, mode]);

    const currentSelected = useMemo(() => {
      return selectedValue !== undefined ? selectedValue : selected;
    }, [selectedValue, selected]);

    const init = useCallback(() => {
      if (!editorInstance.current && editorRef.current) {
        editorInstance.current = new Editor(editorRef.current, {
          isEdit,
          mode: currentMode,
          intersection,
          background: "",
          scroll,
          touch,
          history,
          lineTop,
          grid: {
            size: gridSize,
            fixed: gridFixed,
          },
          onKeydown: (event) => {
            onKeydown?.(event);
          },
          onModeChange: (newMode) => {
            onModeValueChange?.(newMode);
            onModeChange?.(newMode);
          },
          onClick: (event) => {
            onClick?.(event);
          },
          onDrop: (event) => {
            onDrop?.(event);
          },
          onSelect: (event) => {
            onSelectedChange?.(event);
            onSelect?.(event);
          },
          onDragmove: () => {
            onDragmove?.();
          },
          onRemove: () => {
            onRemove?.();
          },
          onMessage: (message) => {
            onMessage?.(message);
          },
          onDo: (event) => {
            onDo?.(event);
          },
          onTouch: () => {
            onTouch?.();
          },
        });
      }
    }, [
      isEdit,
      currentMode,
      intersection,
      theme,
      animation,
      scroll,
      touch,
      history,
      defaultPipeline,
      showBindBtn,
      viewStyle,
      lineTop,
      gridSize,
      gridFixed,
      onKeydown,
      onModeValueChange,
      onModeChange,
      onClick,
      onDrop,
      onSelectedChange,
      onSelect,
      onDragmove,
      onCreateLine,
      onRemove,
      onMessage,
      onDo,
      onTouch,
    ]);

    useEffect(() => {
      init();
    }, [init]);

    useEffect(() => {
      if (editorInstance.current) {
        if (gridSize === 0) {
          editorInstance.current.setGrid(false);
        } else {
          editorInstance.current.setGrid({
            size: gridSize,
            fixed: gridFixed,
          });
        }
      }
    }, [gridSize, gridFixed]);
    useEffect(() => {
      if (editorInstance.current) {
        editorInstance.current.setLineTop(lineTop);
      }
    }, [lineTop]);

    useEffect(() => {
      if (editorInstance.current) {
        editorInstance.current.enableScroll(scroll);
      }
    }, [scroll]);

    useEffect(() => {
      if (editorInstance.current) {
        editorInstance.current.enableTouch(touch);
      }
    }, [touch]);

    useEffect(() => {
      if (editorInstance.current) {
        editorInstance.current.setMode(currentMode);
      }
    }, [currentMode]);

    useEffect(() => {
      if (editorInstance.current) {
        editorInstance.current.options.intersection = intersection;
      }
    }, [intersection]);

    const cancelGroup = useCallback(() => {
      if (currentSelected && editorInstance.current) {
        const group =
          currentSelected.length === 1
            ? currentSelected[0]
            : currentSelected[0].layer;
        if (group.tid()) {
          Modal.confirm({
            title: "提示",
            content: "该组存在物模型信息，取消后将不会恢复，确认取消？",
            okText: "确认取消组合",
            cancelText: "我再考虑考虑",
            onOk: () => {
              if (editorInstance.current) {
                editorInstance.current.cancelGroup(group);
              }
            },
          });
        } else {
          editorInstance.current.cancelGroup(group);
        }
      }
    }, [currentSelected]);

    // Expose methods via ref
    useImperativeHandle(
      ref,
      () => ({
        fit: () => editorInstance.current?.fit(),
        destroy: () => editorInstance.current?.destroy(),
        dragIn: (event, data) => {
          event.dataTransfer?.setData("thing", JSON.stringify(data));
        },
        dropImage: (src, offsetX, offsetY) =>
          editorInstance.current?.dropImage(src, offsetX, offsetY),
        exportPNG: () => editorInstance.current?.exportPNG(),
        exportData: () => editorInstance.current?.exportData(),
        findNode: (nodeId) => editorInstance.current?.findNode(nodeId),
        getAllNodes: () => editorInstance.current?.nodeIds,
        changeElementsPosition: (type) =>
          editorInstance.current?.changeElementsPosition(type),
        group: () => editorInstance.current?.group(),
        cancelGroup,
        pull: (group) => editorInstance.current?.pull(group),
        undo: () => editorInstance.current?.undo(),
        redo: () => editorInstance.current?.redo(),
      }),
      [cancelGroup]
    );

    return (
      <div
        ref={editorWrapRef}
        className="inl-flowchart-editor flex-1"
        style={{ height: "100%" }}
      >
        {(tools || title || extra) && (
          <div className="inl-flowchart-editor-header">
            {title && <div className="inl-flowchart-editor-title">{title}</div>}
            {tools && <div className="inl-flowchart-editor-tools">{tools}</div>}
            {extra && <div className="inl-flowchart-editor-extra">{extra}</div>}
          </div>
        )}
        <div
          ref={editorRef}
          className="inl-flowchart-editor-main w-full h-full" /* style={{ backgroundColor: background }} */
          style={{
            outline: "none",
          }}
        />
      </div>
    );
  }
);

FlowchartEditor.displayName = "FlowchartEditor";

export default FlowchartEditor;

// apps/adminVue/src/components/editor.vue
<script setup lang="ts">
import {
  ref,
  watch,
  computed,
  onMounted,
} from 'vue';
import { useElementSize } from '@vueuse/core';
import _ from 'lodash';
import Editor from '@plux/editor';

import type {
  EditorMode,
  SelectEvent,
  ImageSrc,
  NodeId,
  PositionEnum,
} from '@plux/editor';

const props = withDefaults(defineProps<{
  background?: string;
  isEdit?: boolean;
  mode?: EditorMode;
  intersection?: boolean;
  scroll?: boolean;
  touch?: boolean;
  history?: boolean;
  selected?: SelectEvent;
  gridSize?: number;
  gridFixed?: boolean;
  lineTop?: boolean;
  alignLineFlag?: boolean;
  alignLineOnlySameType?: boolean;
  alignLineFixed?: boolean;
}>(), {
  background: '',
  isEdit: false,
  mode: 'A',
  intersection: false,
  scroll: false,
  touch: false,
  history: false,
  selected: null,
  gridSize: 30,
  gridFixed: false,
  lineTop: false,
  alignLineFlag: false,
  alignLineOnlySameType: false,
  alignLineFixed: false,
});

const emit = defineEmits([
  'click',
  'drop',
  'select',
  'dragmove',
  'update:selected',
  'update:mode',
  'modeChange',
  'keydown',
  'createLine',
  'remove',
  'message',
  'do',
  'touch',
]);

let editor: Editor;

const editorRef = ref();

const { width, height } = useElementSize(editorRef);

const debounceToFit = _.debounce(() => {
  editor.fitStage();
}, 300);

watch([width, height], debounceToFit);

const modeComputed = computed({
  get() {
    return props.mode;
  },
  set(val) {
    emit('update:mode', val);
    emit('modeChange', val);
  },
});

const selectedComputed = computed({
  get() {
    return props.selected;
  },
  set(val) {
    emit('update:selected', val);
    emit('select', val);
  },
});

const init = () => {
  if (!editor) {
    editor = new Editor(editorRef.value, {
      isEdit: props.isEdit,
      mode: props.mode,
      intersection: props.intersection,
      scroll: props.scroll,
      touch: props.touch,
      history: props.history,
      lineTop: props.lineTop,
      grid: {
        size: props.gridSize,
        fixed: props.gridFixed,
      },
      guideLine: {
        enable: props.alignLineFlag,
        sameType: props.alignLineOnlySameType,
        fixed: props.alignLineFixed,
      },
      onKeydown: (event) => {
        emit('keydown', event);
      },
      onModeChange: (mode) => {
        modeComputed.value = mode;
      },
      onClick: (event) => {
        emit('click', event);
      },
      onDrop: (event) => {
        emit('drop', event);
      },
      onSelect: (event) => {
        selectedComputed.value = event;
      },
      onDragmove: () => {
        emit('dragmove');
      },
      onRemove: () => {
        emit('remove');
      },
      onMessage: (message) => {
        emit('message', message);
      },
      onDo: (event) => {
        emit('do', event);
      },
      onTouch: () => {
        emit('touch');
      },
      onContextMenu: (x, y, menuList) => {
        console.log(x, y, menuList);
      },
    })
  }
};

onMounted(() => {
  init();
});

watch(() => props.gridSize, (val) => {
  if (val === 0) {
    editor.setGrid(false);
  } else {
    editor.setGrid({
      size: val,
      fixed: props.gridFixed,
    });
  }
});

watch(() => props.gridFixed, (val) => {
  editor.setGrid({
    size: props.gridSize,
    fixed: val,
  });
});

watch(() => [props.alignLineFlag, props.alignLineOnlySameType, props.alignLineFixed], () => {
  editor.setGuideLine({
    enable: props.alignLineFlag,
    sameType: props.alignLineOnlySameType,
    fixed: props.alignLineFixed,
  });
});

watch(() => props.lineTop, (val) => {
  editor.setLineTop(val);
});

watch(() => props.scroll, (val) => {
  editor.enableScroll(val);
});

watch(() => props.touch, (val) => {
  editor.enableTouch(val);
});

const fit = () => editor.fit();

const exportPNG = () => editor.exportPNG();

const exportData = () => editor.exportData();

const destroy = () => {
  editor.destroy();
};

const dropImage = (src: ImageSrc, offsetX: number, offsetY: number) => {
  editor.dropImage(src, offsetX, offsetY);
};

const setMode = (mode: EditorMode) => editor.setMode(mode);

watch(() => props.mode, (mode) => {
  setMode(mode);
});

const setIntersection = (inter: boolean) => {
  editor.options.intersection = inter;
};

watch(() => props.intersection, (inter) => {
  setIntersection(inter);
});

const findNode = (nodeId: NodeId) => editor.findNode(nodeId);

const getAllNodes = () => editor.nodeIds;

const changeElementsPosition = (type: PositionEnum) => {
  editor.changeElementsPosition(type);
};

const group = () => editor.group();

const cancelGroup = () => {
  const group = selectedComputed.value.length === 1
    ? selectedComputed.value[0]
    : selectedComputed.value[0].layer;
  editor.cancelGroup(group);
};

const editorWrap = ref();

const pull = (group) => editor.pull(group);

const undo = () => editor.undo();

const redo = () => editor.redo();

const centerX = (nodes) => {
  editor.tr.setList(nodes);
  editor.tr.centerX();
  editor.tr.clear();
};

const selectAllType = (type: string) => {
  editor.selectAllType(type);
};

defineExpose({
  fit,
  // resetTexts,
  destroy,
  dropImage,
  setMode,
  exportPNG,
  exportData,
  findNode,
  getAllNodes,
  changeElementsPosition,
  group,
  cancelGroup,
  pull,
  undo,
  redo,
  centerX,
  selectAllType,
});

watch(() => props.background, (val) => {
  editor.changeBackground(val);
});
</script>

<template>
  <div ref="editorWrap" class="editor-wrap" style="height: 100%;">
    <div ref="editorRef" class="editor-main" style="height: 100%; outline: none;"></div>
  </div>
</template>
